components:
  schemas:
    ScanRequest:
      type: object
      properties:
        tr_id:
          type: integer
          format: int32
        profile_id:
          type: string
          format: uuid
        metadata:
          type: object
          properties:
            app_name:
              type: string
            app_user:
              type: string
            ai_model:
              type: string
            csp_vendor:
              type: string
            csp_region:
              type: string
        contents:
          type: array
          items:
            type: object
            properties:
              prompt:
                type: string
              response:
                type: string
      required:
        - tr_id
        - profile_id
        - metadata
        - contents
      
    ScanResponse:
      type: object
      properties:
        report_id:
          type: string
        scan_id:
          type: string
          format: uuid
        profile_id:
          type: string
          format: uuid
        action:
          type: string
        prompt_detected:
          $ref: '#/components/schemas/PromptDetected'
        response_detected:
          $ref: '#/components/schemas/response_detected'
        created_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
      required:
        - report_id
        - prompt_detected
        - response_detected
  
    PromptDetected:
      type: object
      properties:
        url_cats:
          type: boolean
        dlp:
          type: boolean
        injection:
          type: boolean
  
    response_detected:
      type: object
      properties:
        url_cats:
          type: boolean
        dlp:
          type: boolean
  
    Error:
      type: object
      properties:
        status_code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message
info:
  title: AISec API service
  description: "AI Runtime Security scan APIs\
    \ When an AI App user sends prompts or receives responses from AI apps,\
    \ these prompts and responses are sent to AI Security API service to scan the data for threats by subjecting to Security Policy checks\
    \ like Prompt Injection detection, URL filtering and Data Protection (DLP)\
    \ 1. Synchronous API\
    \ 2. Asynchronous API \n"
  version: 0.0.0
openapi: 3.0.3
paths:
  /v1/scan/sync/request:
    post:
      summary: Scan prompt and response for any threats
      description: Post a scan request that returns synchronous response
      security: []
      operationId: ScanSyncRequest
      tags:
        - SyncScanAPIModelAndSchema
      requestBody:
        description: Scan request object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScanRequest'
      responses:
        '200':
          description: successfully scanned request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScanResponse'
        default:
          description: error
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                  error:
                    type: string
servers:
  - url: "http://localhost:39094"
    description: Local Scan service
tags:
  - name: SyncScanAPIModelAndSchema
    description: scan request description


