components:
  schemas:          
    AIProfileObject:
      type: object
      properties:
        profile_id:
          type: string
        profile_name:
          type: string
        csp_id:
          type: string
        tsg_id:
          type: string
        revision:
          type: integer
          format: int32
        active:
          type: boolean
        policy:
          type: string
        created_by:
          type: string
        last_modified_ts:
          type: string
          format: date-time                           
      required:
        - profile_name
        - csp_id
        - tsg_id
        - revision
        - policy
    PaginatedAIProfileObject:
      type: object
      properties:
        ai_profiles:
          type: array   
          items:
            $ref: '#/components/schemas/AIProfileObject'
        next_offset:
          type: integer
          format: int32
info:
  title: AISec API Profile Management service
  description: OpenAPI Specification for the AI Runtime Security API Profile Management Service
  version: 0.0.0
openapi: 3.0.3
paths:
  /v1/mgmt/profile:
    post:
      summary: Request to create a new AI Sec Profile
      description: Post a new AI Sec Profile
      tags:
        - AI Sec Profile
      operationId: CreateNewAIProfile
      requestBody:
        description: AI Sec Profile creation request object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AIProfileObject'
      responses:
        200:
          description: Successfully created a new AI Sec Profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AIProfileObject'
servers:
  - url: "http://localhost:39094/"
    description: Local mgmt profile service
tags:
  - name: AI Sec Profile
  
